trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    chmod +x install-latest-packer.sh
    ./install-latest-packer.sh
  displayName: 'Install packer'

- script: packer validate ubuntu.json
  displayName: 'Run packer validate on ubuntu'

- script: |
    mkdir output-ubuntu-20.04
    packer validate ubuntu-desktop.json
  displayName: 'Run packer validate on ubuntu-desktop'

- script: |
    mkdir -p output-ubuntu-20.04-desktop-hvsocket/packer-hyperv-vmcx
    packer validate ubuntu-enhanced.json
  displayName: 'Run packer validate on ubuntu-enhanced'

- script: packer validate hyperv-windows-10.json
  displayName: 'Run packer validate on windows-10'
