trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      chmod +x install-latest-packer.sh
      ./install-latest-packer.sh
    displayName: 'Install packer'

  - script: packer validate ubuntu.json
    displayName: 'Run packer validate on ubuntu'

  - script: |
      mkdir output-ubuntu-20.04
      packer validate ubuntu-desktop.json
    displayName: 'Run packer validate on ubuntu-desktop'

  - script: |
      mkdir -p output-ubuntu-20.04-desktop-hvsocket/packer-hyperv-vmcx
      packer validate ubuntu-enhanced.json
    displayName: 'Run packer validate on ubuntu-enhanced'

- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: Install-WindowsFeature -Name Hyper-V-PowerShell
    displayName: 'Install Hyper-V Powershell module'

  - powershell: |
      $ChocoInstallPath = "$env:SystemDrive\ProgramData\Chocolatey\bin"

      if (!(Test-Path $ChocoInstallPath)) {
          iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
      }
      choco install packer
    displayName: 'Install packer'

  - powershell: ./windows/scripts/mkiso.ps1 -Source './windows/answer_files/autounattend.xml', './windows/floppy/' -OutPath './windows/iso/floppy.iso' -Force
    displayName: 'Build floppy'

  - script: packer validate hyperv-windows-10.json
    displayName: 'Run packer validate on windows-10'
